### ISSUE TITLE
Implémentation de l'API REST

### ISSUE THREAD

**Issue by AlexandreTO** [antoine-witkowski/diag-plus#2]
# TODO

- [ ] Création de l'API
- [ ] Système de pagination pour l'API
- [ ] Sécurisation de la page / empêcher le libre accès à l'api
